feeds:
  - name: changie
    query:
      headers:
        authorization: "env:GITHUB_AUTH"
        content-type: "application/json; charset=utf-8"
      url: https://api.github.com/graphql
      method: POST
      body: '{ "query": "{
        repository(name: \"changie\", owner: \"miniscruff\") {
          stargazerCount
          forkCount
          issues(states: OPEN) {
            totalCount
          }
        }
      }" }'
      status: 200
    schedule:
      every: 3h
    store:
    - name: stars
      path: "data.repository.stargazerCount"
    - name: issues
      path: "data.repository.issues.totalCount"
    - name: forks
      path: "data.repository.forkCount"

  - name: weather
    query:
      url: https://api.openweathermap.org/data/2.5/onecall
      params:
        APPID: "env:OPENWEATHER_AUTH"
        units: "imperial"
        lat: "env:HOME_LAT"
        lon: "env:HOME_LON"
        exclude: "minutely,current"
      status: 200
    schedule:
      every: 2h
    store:
      - name: sunset
        path: "daily.sunset"
      - name: alertEvents
        path: "alerts.0.event"
      - name: alertDescriptions
        path: "alerts.0.description"
      - name: temperatures
        path: "hourly.#.temp"
        count: 48
      - name: times
        path: "hourly.#.dt"
        count: 48
      - name: icons
        path: "hourly.#.weather.0.icon"
        count: 48
      - name: descriptions
        path: "hourly.#.weather.0.description"
        count: 48
