feeds:
  - name: sample
    query:
      url: http://localhost:8080/static/sample.json
      method: GET
      status: 200
    schedule:
      every: 3h
    store:
    - name: string
      path: "singleString"
    - name: number
      path: "singleNumber"
    - name: arrayStrings
      path: "arrayString"
      isArray: true
    - name: arrayNumbers
      path: "arrayNumbers"
      isArray: true
    - name: objectCereal
      path: "object.inner.cereal"
    - name: objectMilk
      path: "object.inner.milk"
        # - name: arrayObjectNames
        # path: "arrayObjects.#.name"
        # - name: arrayObjectSalaries
        # path: "arrayObjects.#.salary"

dashboard:
  title: "Dashboard"
  # https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name
  meta:
    viewport: "width=device-width, initial-scale=1"
      #layout: 
      # main dashboard body layout, currently hard coded at a 4 column grid
  layers:
    - name: "single-values" # used as an id
      x: 0 # x,y,w,h of our layer in the parent grid
      y: 0
      width: 1
      height: 1
      title: "Singles" # optional text title to add
      layout: two-columns
      contents:
        - type: constant
          styles: ["text-right", "text-large"]
          text: "String"
        - type: text # currently just basic text, image and more later
          styles: ["text-left", "text-large"]
          text: "${data.sample.string}"
        - type: constant # currently just basic text, image and more later
          styles: ["text-right", "text-large"]
          text: "Number"
        - type: text
          styles: ["text-left", "text-large"]
          text: "${data.sample.number}"
