FROM golang:1.17-alpine as build

WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY . .

RUN go build -o web ./web

FROM scratch

COPY --from=build /app/web/web /web
COPY config.yml config.yml

CMD ["/web"]
