FROM golang:1.17-alpine as build

WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY . .

RUN go build -o feed ./feed

FROM scratch

COPY --from=build /app/feed/feed /feed
COPY config.yml config.yml

CMD ["/feed"]
